import React, { useRef, useState } from 'react';
import * as htmlToImage from 'html-to-image';
import { motion } from 'framer-motion';

const ReportCard = ({ score, summary, marketData, risks }) => {
  const cardRef = useRef(null);
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    if (!cardRef.current) return;
    try {
      setExporting(true);
      const dataUrl = await htmlToImage.toPng(cardRef.current, { cacheBust: true, pixelRatio: 2 });
      const link = document.createElement('a');
      link.download = 'AI-CoFounder-Report.png';
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error('Failed to export image', err);
      alert('Failed to export report card.');
    } finally {
      setExporting(false);
    }
  };

  const tamText = marketData?.find(m => m.name === 'TAM')?.text;
  const somText = marketData?.find(m => m.name === 'SOM')?.text;

  return (
    <div className="flex flex-col items-center gap-6 my-8">
      {/* The visible and exportable card */}
      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        ref={cardRef}
        className="w-full max-w-lg bg-[#FAF7F0] p-8 md:p-10 rounded-2xl shadow-lg border border-gray-100 flex flex-col items-center text-center relative overflow-hidden"
      >
        {/* Decorative background element */}
        <div className="absolute top-0 right-0 -mr-16 -mt-16 w-32 h-32 bg-sage opacity-5 rounded-full blur-2xl"></div>
        <div className="absolute bottom-0 left-0 -ml-16 -mb-16 w-32 h-32 bg-sage opacity-5 rounded-full blur-2xl"></div>
        
        <h2 className="text-xl font-medium text-charcoal-muted mb-2 tracking-wide uppercase text-sm">Founder Readiness</h2>
        <div className="text-6xl md:text-7xl font-serif text-sage my-4">
          {score}
          <span className="text-2xl text-charcoal-muted/50 font-sans">/100</span>
        </div>
        <p className="text-sm text-charcoal font-medium mt-2 max-w-sm">
          {score >= 70 ? "High viability with strong market positioning." : score >= 40 ? "Moderate readiness with key strategic hurdles." : "Early concept requiring deeper validation."}
        </p>
        
        <div className="w-full h-px bg-gray-200 my-6"></div>
        
        <div className="w-full text-left space-y-3">
          <p className="text-xs text-charcoal-muted flex items-start gap-2">
            <span className="text-sage mt-0.5">✓</span>
            <span className="line-clamp-2">{tamText ? `TAM: ${tamText}` : 'Market sizing analyzed against historical case studies'}</span>
          </p>
          <p className="text-xs text-charcoal-muted flex items-start gap-2">
            <span className="text-sage mt-0.5">✓</span>
            <span>{risks ? `Market risk ${risks.market_risk}/5, Execution ${risks.execution_risk}/5, Funding ${risks.funding_risk}/5` : 'Risk dimensions analyzed across 4 key vectors'}</span>
          </p>
        </div>
        
        <div className="mt-8 text-xs text-charcoal-muted/50 font-sans">
          Generated by AI Co-Founder Validation Platform
        </div>
      </motion.div>

      <button 
        onClick={handleExport}
        disabled={exporting}
        className="text-sm font-medium bg-charcoal text-white px-6 py-2.5 rounded-full hover:bg-opacity-90 transition-all active:scale-95 disabled:opacity-70 flex items-center gap-2 shadow-sm"
      >
        {exporting ? 'Exporting...' : 'Download Report Card'}
      </button>
    </div>
  );
};

export default ReportCard;
